---
driver:
  name: vagrant
provisioner:
  name: chef_solo
platforms:
- name: ubuntu/precise64
- name: ubuntu/trusty64
- name: ubuntu/xenial64
- name: bento/centos-5.11
- name: bento/centos-6.7
- name: centos/7
- name: oraclelinux-5
  driver_config:
    box: oraclelinux-5
    box_url: http://cloud.terry.im/vagrant/oraclelinux-5-x86_64.box
- name: oracle-6.5
  driver_config:
    box: oraclelinux-6
    box_url: http://cloud.terry.im/vagrant/oraclelinux-6-x86_64.box
- name: oraclelinux-7
  dfiver_config:
    box: oraclelinux-7
    box_url: http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box
- name: bento/debian-6.0.10
- name: debian/wheezy64
- name: debian/jessie64
verifier:
  name: inspec
suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
  verifier:
    inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening
- name: modules_disabled
  run_list:
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening
